version: '2.4'

services:
  map_compute_workers:
    build: .
    environment:
      - report_store_stage
      - worker_count
    volumes:
      - $report_store_stage:/data/report
    command: 
      - /bin/sh
      - -c
      - |
        python scripts/mapshell.py automate-computation

    scale: $worker_count

  map_cleanup_workers:
    build: .
    environment:
      - report_store_stage
    volumes:
      - $report_store_stage:/data/report
    command:
      - /bin/sh
      - -c
      - |
        python scripts/mapshell.py automate-sync-and-cleanup